services:
  web:
    build:
      context: ./
      dockerfile: development.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    image: postgres:16
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      # test: ["CMD-SHELL", "pg_isready -U postgres"]
      # test: pg_isready -U doom -d video_search_frontend_development
      interval: 2s
      timeout: 5s
      retries: 3
    # command: -p 5433

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle:
