# Name of your application. Used to uniquely configure containers.
service: ai-video-search

# Name of the container image.
image: aivideosearch/aivideosearch

# Elastic search url ENV VARIABLE
#ELASTICSEARCH_URL

# Deploy to these servers.
servers:
  web:
    hosts:
      - 5.78.112.67
    labels:
      traefik.http.routers.ai-video-search.rule: Host(`disspell.com`)
      traefik.http.routers.ai-video-search_secure.entrypoints: websecure
      traefik.http.routers.ai-video-search_secure.rule: Host(`disspell.com`)
      traefik.http.routers.ai-video-search_secure.tls.certresolver: letsencrypt
    # options:
    #   network: "private"

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: aivideosearch

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    POSTGRES_DATABASE: "video_search_frontend_production"
    POSTGRES_USER: "postgres"
    # HOST_URL: 5.78.112.67 
    DB_HOST: 5.78.112.67
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    ELASTICSEARCH_URL: 5.78.112.67:9200
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - ELASTIC_PASSWORD
    # - ELASTICSEARCH_URL

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#2a1a2     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:16
    host: 5.78.112.67
    port: 5432
    # options:
    #   network: "private"
    env:
      clear:
        - DB_HOST
        - POSTGRES_USER
        - POSTGRES_DATABASE
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis
    host: 5.78.112.67
    port: 6379
    directories:
      - data:/data

  elastic:
    image: elasticsearch:8.12.2
    host: 5.78.112.67
    port: 9200
    # options:
    #   network: "private"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    env: 
      clear:
        ES_JAVA_OPTS: "-Xms1g -Xmx1g"
          # "-Des.enforce.bootstrap.checks=true"
        # ES_PORT: 127.0.0.1:9200
        discovery.type: single-node
        xpack.security.enabled: true
        xpack.security.http.filter.enabled: true
        xpack.security.http.filter.allow: 5.78.112.67
        xpack.security.http.filter.deny: _all
        xpack.security.transport.ssl.enabled: false
        # locking memory doesn't work and I can't fix it to save my life
        # It does not appear to be needed for production ready elastic
        # bootstrap.memory_lock: true
      secret:
        - ELASTIC_PASSWORD
    volumes:
      - elastic:/usr/share/elasticsearch/data
    cmd:
      - /bin/bash
      - -c
      - |
        # Wait for Elasticsearch to start up before running the setup commands
        until curl -s http://localhost:9200/ > /dev/null; do
          sleep 1
        done
        # Set up passwords for built-in users
        echo "Setting up passwords..."
        bin/elasticsearch-setup-passwords auto --batch --url http://5.78.112.67:9200

# Configure custom arguments for Traefik
# traefik:
#   args:
#     entryPoints.web.address: ":80"
    # accesslog: true
    # accesslog.format: json
traefik:
  image: traefik:v2.11.0
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  # network: "private"
  args:
    entrypoints.web.address: ':80'
    entrypoints.websecure.address: ':443'
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "1337ipJbP7U9mi9cdLngL3g5Napum7tWzM@protonmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /up
  max_attempts: 15
  interval: 20s
#   path: /healthz
#   port: 4000

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Configure the role used to determine the primary_host. This host takes
# deploy locks, runs health checks during the deploy, and follow logs, etc.
#
# Caution: there's no support for role renaming yet, so be careful to cleanup
#          the previous role on the deployed hosts.
# primary_role: web

# Controls if we abort when see a role with no hosts. Disabling this may be
# useful for more complex deploy configurations.
#
# allow_empty_roles: false
